@startuml

header
Jun-15-2021
endheader

title Handle an order

autonumber

activate Client
activate App
activate Repository
activate MessageBus
activate Worker

Client -> App : place order

App -> Repository: place order

Repository -> App: id

App -> Client: order placed

App -> MessageBus: notify placement (id)

Worker <- MessageBus: notify placement (id)

Worker -> Worker: handle placement

Worker -> Repository: update order status

@enduml